Task 1

In [ ]:
import numpy as np
# Task 1
A=np.array([[1,2,1],[-2,1,1]])
B=np.array([[3,1],[-1,0],[2,4]])
C=np.array([[-2,2],[1,-1],[1,2]])
# A+2*B
# B+2*C
dblB=2*B
dblC=2*C
res1=np.dot(A,dblB)
res2=np.dot(A,dblC)
print(res1)
print(res2)

[[  6  10]
 [-10   4]]
[[ 2  4]
 [12 -6]]


Task 2

In [ ]:
import numpy as np
# Task 2
chess88 = np.zeros((8, 8), dtype=int)  # Создаем матрицу 8х8, заполненную нулями

chess88[::2, 1::2] = 1  # Записываем 1 в элементы с четными строками и нечетными столбцами
chess88[1::2, ::2] = 1  # Записываем 1 в элементы с нечетными строками и четными столбцами
print(chess88)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
